name: pagekite-ssh
version: '1'
summary: Connects the local SSH daemon to the Pagekite service
description: |
 Pagekit provides a way to tunnel local TCP traffic to a well
 known name on the Internet. This package makes it so that your
 SSH server is accessible no matter where it sits.

grade: stable
confinement: strict

parts:
  pagekite:
    plugin: autotools
    configflags:
      - --without-java
      - --without-lua
    source: https://github.com/pagekite/libpagekite.git
    build-packages:
      - libev-dev
  snapstuff:
    plugin: dump
    source: snapstuff

apps:
  pagekite-ssh:
    command: pagekite-service
    daemon: simple
    plugs: [network, network-bind]

