name: pagekite-ssh
version: '1'
summary: Connects the local SSH daemon to the Pagekite service
description: |
 Pagekit provides a way to tunnel local TCP traffic to a well
 known name on the Internet. This package makes it so that your
 SSH server is accessible no matter where it sits.

grade: stable
confinement: strict

parts:
  pypagekite:
    plugin: python
    python-version: python2
    source: https://github.com/ted-gould/PyPagekite.git
    after: [pysocksipychain]
  pysocksipychain:
    plugin: python
    python-version: python2
    source: https://github.com/pagekite/PySocksipyChain.git
  snapstuff:
    plugin: python
    python-version: python2
    install: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/snap/hooks
      cp configure_hook.py $SNAPCRAFT_PART_INSTALL/snap/hooks/configure
      cp pagekite-service $SNAPCRAFT_PART_INSTALL/

apps:
  pagekite-ssh:
    command: pagekite-service
    daemon: simple
    plugs: [network, network-bind]

